### ISSUE TITLE
Dark mode switch

### ISSUE THREAD

**Issue by quantuminformation** [breadthe/svelte-tailwind2-starter#1]
Great work, just what I was looking for, nice condense tw 2 integration.

Would be nice to have a UI switch for dark mode.

**Comment by quantuminformation** [comment]
Wonder if its worth showing multiple .env file builds too? ie `.env`, and `.env.staging`, a common use case?

**Comment by breadthe** [comment]
Thanks @quantuminformation ! I just added a dark/light mode switch.

Not sure about `.env`. I haven't really used that in my Svelte projects so far. But then again, I don't have anything major yet, except for an Electron app that doesn't require it yet.

**Comment by quantuminformation** [comment]
nice thx
