### ISSUE TITLE
@apply not working?

### ISSUE THREAD

**Issue by peppobon** [breadthe/svelte-tailwind2-starter#4]
Thanks breadthe for sharing this.
Can you please confirm if @apply are working?
I just did a quick test and classes added using @apply are dropped during compilation.

**Comment by breadthe** [comment]
@peppobon I pushed an update to demonstrate that `@apply` indeed works. Check out `App.svelte` and `global.css`.

Clone the repo, run `yarn install`, then `yarn dev` and you should see the same as the two images in the README.

**Comment by peppobon** [comment]
Ok, I was using @apply from app.svelte/<script>, not from global.css.
Any poiter on why @apply works only if it is called from global.css?

**Comment by breadthe** [comment]
Well, for one thing, the CSS in any Svelte component is scoped to it, so it doesn't have knowledge of weird directives like `@apply`. Second, the bundler itself doesn't know how to handle that (I might be wrong on this one though). Same goes for `.vue` components or other frameworks.

Basically this is how Tailwind has worked so far. You can use directives in CSS/SCSS but not elsewhere.

**Comment by colaho** [comment]
@peppobon check [this](https://dev.to/swyx/how-to-set-up-svelte-with-tailwind-css-4fg5) out. I think this is what you are looking for. I followed the steps and it's able to use @apply directive inside svelte component.
