### ISSUE TITLE
Forms and Typography Plugins

### ISSUE THREAD

**Issue by lsbyerley** [breadthe/svelte-tailwind2-starter#7]
It seems the `@tailwindcss/forms` and `@tailwindcss/typography` plugin styles are not included in the build if you include them in the plugins array of the tailwind config file.

```
const production = !process.env.ROLLUP_WATCH;

module.exports = {
  purge: {
    enabled: production,
    content: ['./src/**/*.html', './src/**/*.svelte'],
    options: {},
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};
```

**Comment by breadthe** [comment]
They are not.
I made this preset for my own use and I haven't needed those plugins yet.
So it's up to each user to add them as they see fit.

**Comment by lsbyerley** [comment]
@breadthe I think i phrased my question wrong. I am including those plugins in my setup, which mirrors yours, and the styles from the those plugins are not working. Is there any other changes that need to be added for them to work?

**Comment by breadthe** [comment]
Got it. I'll reopen this issue until I get a chance to check it out.
I admit I'm a noob in relation to those plugins, but I'll see what I can come up with.

**Comment by lsbyerley** [comment]
> Got it. I'll reopen this issue until I get a chance to check it out.
> I admit I'm a noob in relation to those plugins, but I'll see what I can come up with.

No worries, I can try to pinpoint why its not working as well. I'll report back if i do

**Comment by breadthe** [comment]
I don't see any issues with the typography plugin (unless I'm missing something). I followed the instructions on the plugin page and everything seems to render as expected.

Check it out here in this branch I made: https://github.com/breadthe/svelte-tailwind2-starter/tree/tailwindcss-typography
